language: cpp

compiler:
  - gcc

addons:
  apt:
    packages:
    - libboost-all-dev
    - libeigen3-dev

before_script:
  - ls -ld /usr/include
  - ls -ld /usr/include/boost
  - ls /usr/include/boost
  - cmake .

script:
  - make
  - ctest .
